### ISSUE TITLE
WorkItems linked to the Build/Release and then filter with Query

### ISSUE THREAD

**Issue by gioce90** [BlueBasher/WorkItemUpdater#105]
Hello, actually is possible choose one workitemsSource between
- WorkItems linked to the Build/Release
- Query

I think it would be better if it were possible to choose both, where the "linked" ones are then filtered by a query.

For example, in a pipeline where I deploy multiple work items, but only for a subset (maybe who have a specific Tag) I need to change its status. Using only the "Query" way it would be impossible or too complicated.

**Comment by gioce90** [comment]
Hi @BlueBasher , are you still supporting this project?

**Comment by BlueBasher** [comment]
Hi
Yes, I'm still supporting this project. Only have a shortage on time currently so am not able to implement any new features at this time.
If you're up for it, you could create a PR with the functionality, and I'll make sure I'll look at it ASAP.

**Comment by gioce90** [comment]
Hi @BlueBasher ,

I was wondering, in developing this task, do you have some strategy to debug the task on azure devops or do you proceed by attempts?

**Comment by BlueBasher** [comment]
Hi,

I actually proceed with attempts, and debugging by adding temporary additional logging 🙂
I've found that it's difficult to debug locally since it depends on the build-context.
So I publish a private version of the extension to a sandbox DevOps organization and then run builds on that.
________________________________

**Comment by gioce90** [comment]
Hi @BlueBasher , thank you for your answer. 
Okay, I think I will proceed in the same way. 
I tried publishing on my DevOps organization and do "remote debugging", but is really tricky. I do successful with the "[hub](https://github.com/microsoft/azure-devops-extension-hot-reload-and-debug)" example of MS, but I can't do the same for tasks. Patience.

**Comment by BlueBasher** [comment]
Yes indeed, for my other extension (which is UI extension) I'm able to debug remotely as well.
For task extension I've never found a way to do it, so I've stuck with pushing my local version directly to a sandbox org.

And by the way, thank you for helping out! Think this would be an amazing addition to the extension!

**Comment by dlmarshall3** [comment]
Hi, there! Wanted to see if there is anything we (the people who appreciate your hardwork) could do to help with this. I don't know where to begin to test locally, but something like this would be incredibly helpful to my team, where we are limited to the states we can assign our work items to. IDEALLY, having the ability to filter by Board Colum instead of State would help us immensely, but we would settle for linking to build, plus query. :) Just wish WIQL would let you query releases, pipelines, etc.

**Comment by chrisevett** [comment]
Hey folks, I'm going to take a stab at this unless someone is already working on it. I have an internal ado org I'll be testing with before I send a PR

**Comment by gioce90** [comment]
> Hey folks, I'm going to take a stab at this unless someone is already working on it. I have an internal ado org I'll be testing with before I send a PR

Of course, I'd be really grateful for that too!

**Comment by gioce90** [comment]
Hi @chrisevett  have you some news about this? :)

**Comment by gioce90** [comment]
Amazing! When this would be available? For now I see the version 3 of the task but I don't see the new build&query choice
